tests/wpunit/PostCacheInvalidationTest.php
- This updates the tests to make assertions on the "data" part of the GraphQL payload, not the entire GraphQL payload
=> bugfix: #154 - Fix broken tests in PostCacheInvalidation test suite

src/Admin/Settings.php, src/Document/MaxAge.php, tests/functional/DocumentMaxAgeCest.php, tests/wpunit/BatchQueryTest.php
Hello! Great work on this plugin. I'm digging in and building a integration with WordPress VIP's platform to automatically purge page cache when this plugin is in use.
This PR introduces a few changes:
- Remove references to and control over the [`Access-Control-Max-Age` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Max-Age), which is a CORS response header. This header has nothing to do with whether a response body is cached by the browser or any other cache. It would be unexpected for this plugin to change the global CORS behavior of WPGraphQL.
- Improve the validation of the `global_max_age` option. Currently, an empty input is coerced to `0` on save, making it very easy for a plugin user to accidentally disable caching without realizing it.
- Improve …
=> Improve Cache-Control header implementation

src/Document.php, wp-graphql-smart-cache.php
This adds support for the x-graphql-key headers to work when a query is referenced by queryId
When querying via queryId, most headers related to caching are missing. This PR fixes that.
**Before**
Querying for a query using a `queryId` only returns the `graphql:Query` X-Key header, and doesn't include the node/list/queryId, keys.
**After**
After this PR, the node/list/queryId keys are properly output with the response.
=> Better queryId support for query analyzer

src/Cache/Invalidation.php, wp-graphql-smart-cache.php
When installing the plugin from Composer, the autoload.php will exist in the project installing the plugin, not in the plugin itself. 
This wraps the the autoload `require` in a `file_exists()` check before requiring the local plugin autoload.
Additionally, this adds a check for the `Document` class in the `can_load_plugin` function to ensure the autoloaded classes exist before using them.
Closes #176
=> fix: prevent error when users install the plugin from Composer

src/Cache/Invalidation.php, src/Cache/Results.php, tests/functional/AdminSettingsGrantCest.php, tests/wpunit/CachedQueryTest.php
This PR adds a new `graphql_cache_is_object_cache_inabled` filter that can allow 3rd party developers to dynamically enable/disable the object cache.
For example, (as mentioned in #177) a query param in the request, such as `?disable_cache` could be read by this filter and disable the cache for that request. 
This filter could be used like so:
```php
add_filter( 'graphql_cache_is_object_cache_enabled', function( $enabled, $request ) {
// disable caching when `?disable_cache` is included as a query param
if (
$_SERVER['REQUEST_METHOD'] === 'POST' &&
isset( $_REQUEST['disable_cache'] )
) {
return false;
}
return $enabled;
}, 10, 2 );
```
=> feat: add new "graphql_cache_is_object_cache_inabled" filter 

readme.txt, wp-graphql-smart-cache.php
- ([#178](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/178)): feat: add new "graphql_cache_is_object_cache_enabled" filter
- ([#179](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/179)): fix: prevent error when users install the plugin with Composer
=> release: v0.3.2

README.md
"Missing Invalidation Hooks" section referenced the issue but did not link to it - link added here.
=> Add reference to Settings invalidation issue

wp-graphql-smart-cache.php
- update constant name to check the min WPGraphQL version. The constant name was the same as the constant defined in WPGraphQL for ACF extension, so the version check was sometimes using that constant, depending on the order of activation
=> fix: update constant name for min required version of WPGraphQL

wp-graphql-smart-cache.php
For purge_all action, send purge to varnish for the highest level graphql hash key.  Expecting varnish cache to invalidate all cached graphql queries for the domain/endpoint.
re: [issue](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/193)
=> Add action on purge-all to send purge to WPE varnish

docs/object-cache.md, docs/persisted-queries.md
This PR fixes broken links in the documentation.
Thanks for building this plugin and taking the time to write such good documentation 🚀
=> fix: update documentation links

composer.lock, src/Document.php, src/Document/Grant.php, src/Document/MaxAge.php, tests/functional/AdminEditorDocumentCest.php, tests/functional/DocumentCest.php
Sitemaps and endpoints for graphql_document, grant, max_age are visible at endpoints. Disable these and try to test some endpoints.
Related [issue](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/198)
=> Disable public query for taxonomies for saved queries

src/Cache/Invalidation.php
**ErrorException**
`Warning: Attempt to read property "post_type" on null
`
In this updated code, the condition $post checks whether the $post variable is not null before accessing its post_type property. If $post is null, the code immediately returns without attempting to access its properties.
=> Fix: ErrorException Warning: Attempt to read property "post_type" on null

readme.txt, wp-graphql-smart-cache.php
- [#202](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/202) fix: ErrorException Warning: Attempt to read property "post_type" on null. Thanks @izzygld!
=> release: v1.0.2

src/Cache/Invalidation.php, tests/wpunit/UserCacheInvalidationTest.php
This ensures that updates to the "apple_news_notice" meta key do not trigger cache purges. 
closes: #206
- Failing test: https://github.com/wp-graphql/wp-graphql-smart-cache/actions/runs/4734838056/jobs/8404287632#step:8:5613
- Passing test:  https://github.com/wp-graphql/wp-graphql-smart-cache/actions/runs/4734919202/jobs/8404484191?pr=207#step:8:6015
=> fix: ignore purging after updates to "apple_news_notice" meta key

src/Cache/Invalidation.php
Fixing:
**ErrorException**
Warning: Attempt to read property `"post_type"` on null.
**Solution:**
> The error message you are seeing suggests that the $post object is null, which means that it was not able to retrieve the post object using the get_post() function.
Here are a few things you can try to resolve this issue:
Check if `$post_id` is valid: Make sure that `$post_id `is a valid post ID. You can check if it is by using the` post_exists() function:`
=> add: fix for empty post id's

readme.txt, wp-graphql-smart-cache.php
- [#210](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/210) fix: fixes a regression to v1.0.3 where `post_exists()` was being called even though the `post_exists` function doesn't exist in this context. Instead this checks `instanceof WP_Post` instead.
=> release: v1.0.4

src/Cache/Invalidation.php
This PR changes the actions that are listened to for purging tags. 
Instead of purging in response to the `edited_term_taxonomy`, which gets called when a post associated with a term is updatated, even when the term relationship hasn't changed, this now responds to the `added_term_relationship` and `deleted_term_relationship` hooks, as well as the `saved_term` hook. 
In addition, this adds logic to the transition post status callback to also call the added/deleted term relationship callbacks.
=> fix: #212 over purging tags

src/Cache/Invalidation.php, tests/wpunit/MenuCacheInvalidationTest.php
- Updates `is_menu_public` to determine whether a menu is public from the Model, instead of hard-coded logic about the locations
closes #220 
~(needs a test still)~
=> fix: updating menus not assigned to locations doesn't purge menus, even if their model is public

src/Cache/Invalidation.php
This PR updates the purge events that are called in response to term updates. 
When a term is saved, this adds the previously missing event name "term_saved" and when a term is removed from being associated with an object, this adds the previously missing event name "term_relationship_deleted".
Additionally, when an object is associated with a term the callback no longer calls purge on `list:$taxonomy_name`
=> fix: update term action purge calls

tests/functional/MutationsCest.php, wp-graphql-smart-cache.php
The goal of this PR is to fix a bug where mutations are being cached. Mutations should not be cached. 
This adds a (failing) test which should help guide us to a solution.
=> fix: mutations shouldn't be cached

phpstan.neon.dist, src/Admin/Editor.php, src/Admin/Settings.php, src/AdminErrors.php, src/Cache/Collection.php, src/Cache/Invalidation.php, src/Cache/Query.php, src/Cache/Results.php, src/Document.php, src/Document/Description.php, src/Document/Grant.php, src/Document/Loader.php, src/Document/MaxAge.php, src/Storage/Ephemeral.php, src/Storage/Transient.php, src/Storage/WpCache.php, src/Utils.php, src/ValidationRules/AllowDenyQueryDocument.php, wp-graphql-smart-cache.php
Increase and fix phpstan levels 5 and 6.
Reference [issue](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/238)
=> Phpstan level 5,6

composer.lock, phpstan.neon.dist, src/Admin/Editor.php, src/AdminErrors.php, src/Cache/Collection.php, src/Cache/Invalidation.php, src/Cache/Query.php, src/Cache/Results.php, src/Document.php, src/Document/MaxAge.php, src/Utils.php
Fixes for phpstan levels 6 and 7.
[Issue](https://github.com/wp-graphql/wp-graphql-smart-cache/issues/238) reference
=> Phpstan level 7 changes

composer.lock, src/Admin/Editor.php, src/AdminErrors.php, tests/acceptance/QueryIdCest.php, tests/functional/AdminEditorDocumentCest.php, tests/functional/AdminSettingsCacheCest.php
When editing saved persisted queries in WP admin editor, do not allow invalid queries to be published.  But allow invalid queries to be saved as drafts.
closes #243
=> Handle errors when editing queries in admin editor

.env.dist, .env.testing, .github/workflows/tests-wordpress.yml, .github/workflows/upload-plugin-zip.yml, .github/workflows/wordpress-coding-standards.yml, composer.lock, docs/development.md
Add WP 6.3 to the CI/CD test matrix.  Change documentation references for the WP_VERSION and PHP_VERSION variables to 6.3 and 8.2, respectively.  
closes #250 
[dependency](https://github.com/wp-graphql/wp-graphql/pull/2907) - on wp-graphql 6.3 image being merged and tagged in an upcoming release.
=> ci: Add WP 6.3 to test matrix. Update docs to reflect

composer.json
Namespaces: https://github.com/search?q=repo%3Awp-graphql%2Fwp-graphql-smart-cache%20path%3A%2F%5Esrc%5C%2F%2F%20namespace&type=code
=> Remove invalid namespaces from autoloading

.github/workflows/code-quality.yml, .github/workflows/tests-wordpress.yml, composer.lock, readme.txt, src/Cache/Collection.php, wp-graphql-smart-cache.php
- updates tests to test against WordPress 6.4
- updates README, plugin file accordingly
closes #263
=> ci: update tests to test against WordPress 6.4

readme.txt, wp-graphql-smart-cache.php
- [#266](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/266): ci: update tests to run against WordPres 6.4
- [#266](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/266): fix: ensure store_content() is passed a string to adhere to phpstan standards
- [#262](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/262): fix: remove invalid namespaces from autoloading. Thanks @szepeviktor!
- [#251](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/251): ci: add WP 6.3 to test matrix
- [#258](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/258): ci: add build-plugin command to set up no-dev
=> release: v1.2.1

src/Admin/Settings.php, tests/wpunit/AdminSettingsCacheTest.php
This force enables the GraphQL Query Analyzer when WPGraphQL Smart Cache is active. 
In v1.20.0 of WPGraphQL the GraphQL Query Analyzer became optional, causing some users of WPGraphQL Smart Cache to lose the X-GraphQL-Keys header used by cache tagging and cache invalidation. 
This force enables the Query Analyzer when using WPGraphQL Smart cache, ensuring that the keys are generated and output in the headers.
Closes: #269 #268 
Related: 
- https://github.com/wp-graphql/wp-graphql/pull/3008
- https://github.com/wp-graphql/wp-graphql/pull/3025
=> feat: force enable query analyzer

readme.txt, wp-graphql-smart-cache.php
- [#270](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/270): feat: force enable query analyzer. **This fixes a regression to WPGraphQL Smart Cache users caused by the WPGraphQL v1.20.0 release, where the Query Analyzer became optional and defaulted to "off"**. WPGraphQL Smart Cache now force-enables the Query Analyzer to support Cache tagging and tag-based cache invalidation.
=> release: v1.3.0

src/Cache/Invalidation.php, tests/_support/TestCase/WPGraphQLSmartCacheTestCaseWithSeedDataAndPopulatedCaches.php, tests/wpunit/MenuCacheInvalidationTest.php, tests/wpunit/MenuItemCacheInvalidationTest.php, tests/wpunit/PostCacheInvalidationTest.php
This adds event listeners for when menu items are created, updated and deleted to purge associated caches in response to said events.
closes #260
=> fix: invalidate caches for menu items

src/Admin/Settings.php
This PR updates the "GraphQL > Settings > Cache" settings page to provide more clarity on the settings and improve the visual hierarchy and organization of settings. 
The settings were a bit hard to understand. They weren't logically separated and lacked full descriptions of their impact and associations with the other settings.
Now the settings are grouped by related settings: Network Cache, Object Cache and Debugging, and each "group" has a description providing more clarity and recommended usage.
=> fix: improve clarity on Cache settings page

readme.txt, wp-graphql-smart-cache.php
- [#273](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/273): fix: improve clarity on Cache settings page
- [#272](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/272): fix: invalidate caches for menu items
=> release: v1.3.1

readme.txt, wp-graphql-smart-cache.php
- [#278](https://github.com/wp-graphql/wp-graphql-smart-cache/pull/278): ci: Update tests to run against WordPress 6.5
=> release: v1.3.2

.phpcs.xml.dist, src/Admin/Editor.php
This PR restores some rules that auto-format trailing whitespace and newlines in PHPCBF. I copied the code from: https://github.com/AxeWP/WPGraphQL-Coding-Standards/commit/23dbbaf8f91c4cb596116c4c5415b4e70c5b50f7 (thanks @justlevine)
Example from before these rules are reintroduced; the formatter ignores these spacing issues:
With the rules reintroduced, the file is formatted as expected, with extraneous whitespace removed:
I attempted to try installing WPGraphQL CS from [here](https://github.com/AxeWP/WPGraphQL-Coding-Standards?tab=readme-ov-file#installation) using `composer require --dev axepress/wp-graphql-cs` to see if we could use a single source of rulesets, but I ran into this error:
I'm not sure if it's worth pursuing to use the single code rule source, or if it's a rabbit hole I …
=> fix: restore whitespace rules for PHPCBF

src/Document.php
This fixes a bug where using all lowercase `queryid` as a GET param would execute the query but would not include the X-GraphQL-Keys in the response, preventing the documents from being properly tagged in the cache and thus not being invalidated from the cache properly.
Executing a GET request with `queryid` as the query param leads to X-GraphQL-Keys being excluded from the response
Now using lowercase `queryid` or camelcase `queryId` both work and return the X-GraphQL-Keys:
`queryid`:
`queryId`:
----
closes: #293
=> fix: queryid not returning X-GraphQL-Keys headers

.github/workflows/tests-wordpress.yml, composer.json, composer.lock, readme.txt, src/Document/Loader.php, src/ValidationRules/AllowDenyQueryDocument.php, wp-graphql-smart-cache.php
This updates a few methods that were changed in graphql-php and were updated as part of the WPGraphQL v2.0 release. 
- update `setPersistentQueryLoader` to `setPersistedQueryLoader` per graphql-php
- update `getVisitor` to accept `QueryValidationContext` instead of `ValidationContext` per graphql-php
NOTE: WPGraphQL Smart Cache must be updated to v2.0+ in order to use it with WPGraphQL v2.0+ (and vice versa).
=> fix: update dependencies for WPGraphQL v2.0 compatibility
